language: julia
os:
  - linux
  - osx
julia: 
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly

notifications:
  - email: false
script:
  - while sleep 30; do echo "still alive"; done &
  - julia -e 'using Pkg; Pkg.add("https://github.com/erou/LatticeGFH90.jl");'
  - julia -e 'using Pkg; Pkg.test("LatticeGFH90")'
